general:
  buildTool: 'mta'
  manualConfirmation: true
stages:
  Acceptance:
    deployTool: 'mtaDeployPlugin'
    mtaDeployParameters: '--version-rule ALL'
    cloudFoundry:
      org: 'OpenSAP-DEV'
      space: 'dev'
      credentialsId: 'cfDeploy'
  Release:
    mtaPath: 'DemoApp.mtar'
    nodeName: 'OpenSAP_DEV'
    credentialsId: 'tms'
steps:
  artifactSetVersion:
    commitVersion: false
    
