general:
  buildTool: 'mta'
  manualConfirmation: false
stages:
  Release:
    deployTool: 'mtaDeployPlugin'
    mtaDeployParameters: '--version-rule ALL'
    cloudFoundry:
      org: 'OpenSAP-DEV'
      space: 'dev'
      credentialsId: 'cfDeploy'
    mtaPath: 'DemoApp.mtar'
    nodeName: 'OpenSAP_QA'
    credentialsId: 'tms'
steps:
  artifactPrepareVersion:
    versioningType: 'cloud_noTag'
  artifactSetVersion:
    commitVersion: false
    
